### ISSUE TITLE
Handle Errors On Payment Screen

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/giving-frontend#554]
There needs to be a case for errors and tests for those. Authorize provides guidance for the potential errors returned.

https://developer.authorize.net/api/reference/features/accept_hosted.html#Error_and_Fraud_Filter_Handling

**Acceptance Criteria**

- [ ] Read sandbox testing guide: https://developer.authorize.net/hello_world/testing_guide.html
- [ ] Come up with specific tasks from the testing guide
- [ ] Add Cypress tests for handling payment errors
- [ ] Document errors in authorize workflow document

**Comment by mattroush** [comment]
@alexfinnarn Some notes I dug up and updated, which we can create documentation from:

The nice thing about using the hosted form is that it handles most errors for us. If they haven’t completed all fields properly or the payment is declined for any reason, Auth.net displays the error in the form and they can correct it or leave right there.

The Response Code from Authorize.net is what we really care about here. I’ve detailed them here, but we should really only ever encounter 1 and 4. Both 1 and 4 are treated as successful payments from the website’s perspective, but are treated differently on the auth.net side.

**1 - Successful payment**
Nearly all payments should return this response code. This can mean one of two things:
- absolutely no issues with the payment
- it may have triggered an FDS filter, but the filter is set to “Process as normal and report filter(s) triggered”. So the payment is treated as successful but flagged in Authorize.net for CUF in case they want to investigate anything.

**2 - Decline from the card company or Fraud Detection Suite (FDS)**
We should not see these unless we subscribe to the specific webhook for them because the form handles them for us.
Examples:
- bank account is closed (card company)
- billing address and zip don’t match what bank has on file (FDS)
- CVV doesn’t match (FDS)

**3 - Decline because of an “error,” like expired credit card**
We also shouldn’t see any responses with this response code, either, because, again, the form handles them for us.

**4 - Hold for Review**
We may encounter this one. This response code is returned when a payment triggers an FDS filter that is set to either “Authorize and Hold for Review” or “Do not authorize, but hold for review” — the latter meaning don’t even attempt to check with the bank yet.

On the website side, we treat this the same as a successful payment. On the Authorize.net side, regardless of which type of hold it is, these are captured under “Suspicious Transactions” and will not be fully processed until CUF reviews and approves them. If they decide not to approve one, they will contact the donor (if appropriate) and update donation records in source system accordingly.

We don’t currently have many FDS filters set to use this option, but those we do have include:
- Velocity Filters — once transactions exceed the set velocity, every every subsequent transaction will be flagged and held for review
	- Daily (currently 200)
	- Hourly (currently 40)
	- Transaction IP (currently 5 per IP per hour)
- Authorize.net has a mysterious “Suspicious Transactions Filter” that they control and triggers Hold for Review
- Amount Filter (currently min: $2 and max: $25000)
- Regional Filter
	- Currently, gifts from an IP in Africa, Asia and South America are held and flagged for review. These locations have been associated with past fraud. May need to add India to the list, too.
