### ISSUE TITLE
`allocation_code` query parameter

### ISSUE THREAD

**Issue by mattroush** [CUCentralAdvancement/giving-frontend#569]
`allocation_code` is one of [the custom query parameters](https://github.com/CUCentralAdvancement/giving-frontend/blob/main/docs/custom-query-params.md) users can leverage, especially in cases where marketing automation platforms are able to generate unique links per recipient based on data from Advance (e.g. most recent gift fund).

Used in place of the fund page path/slug, redirects to fund page if one with provided allocation code exists and is active. If part of a query string, additional parameters should be retained upon redirect.

**Use Case:** For mass email solicitation, link each donor to fund of most recent gift using Advance data and custom script.

**Validation:** Value must be 7 digits (6 real numbers + leading zero).<br />✅ : `giving.cu.edu?allocation_code=0221052`<br />❌ :  `giving.cu.edu?allocation_code=221052`

### Acceptance Criteria

- [ ] site reads allocation_code value and, if associated fund is published and active, site redirects user to corresponding fund's page.
- [ ] If param is part of a query string, all other parameters are retained in URI after redirect.
- [ ] If fund is published but not active, site follows inactive fund redirect behavior _**(capture in new dev task)**_.
- [ ] if fund is not published or if value is not valid, site follows write-in fund redirect behavior _**(capture in new dev task)**_.

### Next Issue

Deploy and test.

**Comment by alexfinnarn** [comment]
@mattroush This feature is harder to do with static site generation than it was on Drupal 7. However, if this is done server-side currently, then I think it would have failed for Fastly served pages. There needs to be some sort of JS code to run. I have wondered about the D7 site and its caching behavior if this feature works all the time now, but I don't know much about the VCL configuration.

Since the allocation code is known when the user requests the site, it would be far easier to just send them to the fund's detail page. I wonder if this can be done with an API call within MC/Salesforce or even to the CMS when the email list is being created. To me, it doesn't make sense to redirect someone when you know the fund they will go to ahead of time. 

If MC places the fund detail page link, then the only code to add is dealing with unpublished/deactivated fund requests and redirecting users in that case. However, even that redirect doesn't need to happen here since the API can return the matching fund to the allocation code or the redirect fund if that one is deactivated. 

I always like to correct data at the source, if possible, rather than pushing out bad data/broken links when those can be filtered...plus, I'd think tracking would be easier this way. Users would enter the fund detail page without redirects and chance to erase params. Thoughts?

**Comment by alexfinnarn** [comment]
placing as blocked since this is larger than amending acceptance criteria.

**Comment by mattroush** [comment]
@alexfinnarn MC isn't the only place this is used, and not all systems know the fund path (e.g. Advance). The original need was the for the emails that come from the call center when someone commits to making a gift over the phone -- the emails needed to link to the fund they committed to giving to (of active) but the vendor who manages the call center and it's tech systems can't or aren't willing to build out functionality to map the allocation codes they already have in their system to a new table somewhere that gets populated regularly somehow with updated paths for each allocation.

**Comment by mattroush** [comment]
I should add -- "allocation code" will become legacy a year from now. So while I think marketing automation will be improved by a way to route using a common ID that spans systems, the way it works today doesn't have to be the way it works tomorrow.

**Comment by alexfinnarn** [comment]
taking off pinned so Stalebot can do its business.
