### ISSUE TITLE
Create /faqs and /faqs/[slug].js pages

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/giving-frontend#573]
The FAQ data is in the CMS and has two API endpoints. Now, the frontend can load and loop through those to create the /faq page. I do wonder if it is worth it to have the `/faq/*` pages and instead jump to the FAQ for those URLs. I like that idea best so I will set it up for a demo.

**Acceptance Criteria**

- [x] New `/faqs` page that lists all FAQs
- [x] Start of `/faqs` has the question titles as links to the answer
- [x] Answer has a `#question-title` header used for the link and whatever detail
- [x] FAQ answers are always shown and not accordions
- [x] `/faqs/[slug]` shows an individual question and answer
- [x] Add tests for navigating FAQ page

**Next Issue**

The FAQ pages had weird ids like `t1204n7594` that appears to be the combination of category taxonomy ID as well as the FAQ node ID. Do these need to be preserved? Do people really link to them? Can we get evidence from GA?

**Comment by mattroush** [comment]
I'll see if I can pull a report from Google Analytics to see if anyone is landing on the anchor links. We originally designed the page so you link straight to the question with the answer expanded -- which is why those weird id links exist. There have been some use cases where being able to go straight to a separate page for the FAQ was needed, but not sure that's actually necessary if the new one works as described. So, I think your single page solution should work just fine so long as answers can contain images and rich text.

**Comment by alexfinnarn** [comment]
MVP work is done...

- listing page - https://giving-frontend.herokuapp.com/faqs
- detail page - https://giving-frontend.herokuapp.com/faqs/what-are-one-time-gifts
